name = "lechpol-logistics-park"
pages_build_output_dir = "./dist"

# Default / Preview Environment (Gałąź 'dev' lub wersje zapoznawcze)
[[d1_databases]]
binding = "DB"
database_name = "lechpol-db" # Nazwa Twojej obecnej bazy dev
database_id = "6474f8a1-5247-45e6-b253-3dc9e91d16de"

# Production Environment (Gałąź 'main' / domena produkcyjna)
[env.production]
[[env.production.d1_databases]]
binding = "DB"
database_name = "lechpol-db-prod" # Nazwa nowej bazy prod
database_id = "fee2a2dd-cab3-4276-ba3c-5e079c81519b"